### ISSUE TITLE
Why defining variables into `vars/` instead of `defaults/`?

### ISSUE THREAD

**Issue by mathieumd** [ipr-cnrs/glpi-agent#1]
Thanks for writing this role!

At work, we prefer to always mirror remote source of binaries. Therefore, we need to overload [`glpi_agent__package_url`](https://github.com/ipr-cnrs/glpi-agent/blob/master/vars/Debian.yml#L23) from `https://github.com/glpi-project/glpi-agent/...` to our own internal web server. (*We could also deploy our own APT repo, but that's another story...*)

Unfortunately, it's defined into `vars/` instead of `defaults/`, and therefore (AFAIK) cannot be redefined through inventory variables. Is this locking really necessary for this specific variable?

**Comment by gardouille** [comment]
My first thought: because it's a simple legacy of my previous role https://github.com/ipr-cnrs/fusioninventory
As it supported several distributions, I had put everything concerning Debian in the dedicated `vars/` file.

But... checking the history, I've just noticed that I'd moved it back into `defaults/` :sweat_smile: 
https://github.com/ipr-cnrs/fusioninventory/commit/ab1e1ca2b4dc7bdf09601c937e3a92d4b131351a

So I'm going to put it back in `defaults/` for glpi-agent too :+1:

**Comment by gardouille** [comment]
A new v1.1.2 release is available but… there have been some changes to Ansible Galaxy.
I'm looking at the new way to upload content ^^

**Comment by mathieumd** [comment]
Thank you! m(_ _)m
